on:
  release:
    types: [created]

jobs:
  build:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions/setup-rust@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Add macOS target for Rust
        run: rustup target add x86_64-apple-darwin
        if: matrix.target == 'x86_64-apple-darwin'

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: stable
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          
    # Conditional runner for macOS and Ubuntu based on the target
    runs-on: ${{ matrix.target == 'x86_64-apple-darwin' && 'macos-latest' || 'ubuntu-latest' }}
